name: zcm-docker-compose
services:
  zcm-api:
    build:
      context: ..
      dockerfile: .\src\ZSocialMedia.WebApi\Dockerfile
      target: final
    container_name: zcm-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health", "||", "exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
      
  postgres:
    image: postgres:16-alpine
    container_name: zcm-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: zcm_db
      POSTGRES_USER: zcm_user
      POSTGRES_PASSWORD: admin_password
      POSTGRES_INITDB_ARGS: "--data-checksums"

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./postgres/scripts/init-db.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./postgres/backups:/backups

    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zcm_user -d zcm_db"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s

  redis:
    image: redis:8-alpine
    container_name: zcm-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./redis/scripts:/scripts:ro
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    name: zcm-network
    driver: bridge
